Enable slurm_nss plugin
aws/aws-parallelcluster-cookbook pull request #1343
Opened 2022-01-27 21:21 UTC by hanwen-pcluste

The plugin can be turned off by setting `enable_nss_slurm` to `false`

Signed-off-by: Hanwen <hanwenli@amazon.com>

### Tests
* Describe the automated and/or manual tests executed to validate the patch.
All tests in pcluster3.yaml have been passed.
test_ad_integration with MicrosoftAD has been passed

### References
* Link to related PRs in other packages (i.e. cookbook, node).
* Link to documentation useful to understand the changes.

### Checklist
- [ ] Make sure you are pointing to **the right branch** and add a label in the PR title (i.e. **2.x** vs **3.x**)
- [ ] Check all commits' messages are clear, describing what and why vs how.
- [ ] Make sure **to have added unit tests or integration tests** to cover the new/modified code.
- [ ] Check if documentation is impacted by this change.

Please review the [guidelines for contributing](../CONTRIBUTING.md) and [Pull Request Instructions](https://github.com/aws/aws-parallelcluster/wiki/Git-Pull-Request-Instructions).

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-01-27 21:38 UTC, charlesg3 commented on attributes/default.rb
> +default['cluster']["enable_nss_slurm"] = "true"
single quotes

2022-01-27 21:40 UTC, charlesg3 requested changes
comments inlined.

2022-01-27 22:48 UTC, hanwen-pcluste commented on attributes/default.rb
> +default['cluster']["enable_nss_slurm"] = "true"
Done

2022-01-27 22:50 UTC, charlesg3 approved these changes, later dismissed

2022-01-28 19:05 UTC, charlesg3 commented on attributes/default.rb
> +default['cluster']["enable_nss_slurm"] = node['cluster']["directory_service"]["enabled"]
single quotes

2022-01-28 19:37 UTC, hanwen-pcluste commented on attributes/default.rb
> +default['cluster']["enable_nss_slurm"] = node['cluster']["directory_service"]["enabled"]
Done

2022-01-28 20:12 UTC, charlesg3 approved these changes

2022-01-28 20:18 UTC, merged

2022-02-01 10:17 UTC, demartinofra commented on cookbooks/aws-parallelcluster-slurm/templates/default/slurm/slurm.conf.erb
> +LaunchParameters=enable_nss_slurm
if not done already we need to call this out explicitly in changelog ince there might be users adding LaunchParameters in Slurm config already

2022-02-01 10:17 UTC, demartinofra commented on cookbooks/aws-parallelcluster-slurm/recipes/config_compute.rb
> +end
what about a kitchen test for this?