[develop] Change default TreeWidth value
aws/aws-parallelcluster-cookbook pull request #2008
Opened 2023-04-14 07:44 UTC by NSsirena

### Description of changes
* Change default value to TreeWidth
 
As a result of fanout investigation we decided to set the default TreeWidth value to 30 since it is the best balance between performances and robustness

### Tests
* Tests were made during the fanout investigation

### Checklist
- [x] Make sure you are pointing to **the right branch** and add a label in the PR title (i.e. **2.x** vs **3.x**)
- [x] Check all commits' messages are clear, describing what and why vs how.
- [x] Make sure **to have added unit tests or integration tests** to cover the new/modified code.
- [x] Check if documentation is impacted by this change.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2023-04-14 11:08 UTC, jdeamicis requested changes

2023-04-14 11:08 UTC, jdeamicis commented on cookbooks/aws-parallelcluster-slurm/templates/default/slurm/slurm.conf.erb
> +TreeWidth=30
This is not where the default TreeWidth is set. This is a special case when the DNS resolution is disabled.

2023-04-14 11:23 UTC, jdeamicis submitted a review, later dismissed

2023-04-14 14:52 UTC, enrico-usai commented on CHANGELOG.md
> +- Set Slurm default TreeWidth to 30
minor: missing final dot
minor: use backtick for TreeWidth

2023-04-14 14:52 UTC, enrico-usai commented on CHANGELOG.md
> +- Set Slurm default TreeWidth to 30
What about: "Set default value for Slurm `TreeWidth` to 30."

2023-04-17 06:51 UTC, NSsirena commented on CHANGELOG.md
> +- Set Slurm default TreeWidth to 30
Thanks for spotting this.
Fixing it.

2023-04-17 08:57 UTC, jdeamicis approved these changes

2023-04-17 08:57 UTC, merged